plugins {
    id 'com.android.application'
}

android {
    namespace 'com.shiguangbox.pet'
    compileSdk 35

    defaultConfig {
        applicationId 'com.shiguangbox.pet'
        minSdk 26
        targetSdk 32
        versionCode 120
        versionName '1.2.0'
    }

    buildTypes {
        debug {
            minifyEnabled false
        }
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
