package com.shiguangbox.app

import android.app.NotificationChannel
import android.app.NotificationManager
import android.content.Context
import androidx.core.app.NotificationCompat
import androidx.work.*
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import java.time.Duration
import java.time.LocalDate
import java.time.LocalTime
import java.time.ZonedDateTime
import java.time.format.DateTimeFormatter
import java.util.concurrent.TimeUnit

object DailySummaryScheduler {

    private const val UNIQUE_WORK = "shiguangbox_daily_summary"

    fun schedule(context: Context, timeText: String) {
        val targetTime = runCatching {
            LocalTime.parse(timeText, DateTimeFormatter.ofPattern("HH:mm"))
        }.getOrElse { LocalTime.of(22, 30) }

        val now = ZonedDateTime.now()
        var next = now.toLocalDate().atTime(targetTime).atZone(now.zone)
        if (!next.isAfter(now)) next = next.plusDays(1)

        val delayMillis = Duration.between(now, next).toMillis().coerceAtLeast(1000)

        val request = OneTimeWorkRequestBuilder<DailySummaryWorker>()
            .setInitialDelay(delayMillis, TimeUnit.MILLISECONDS)
            .build()

        WorkManager.getInstance(context).enqueueUniqueWork(
            UNIQUE_WORK,
            ExistingWorkPolicy.REPLACE,
            request
        )
    }
}

class DailySummaryWorker(
    appContext: Context,
    params: WorkerParameters
) : CoroutineWorker(appContext, params) {

    override suspend fun doWork(): Result {
        val context = applicationContext
        val prefs = context.getSharedPreferences("shiguangbox_settings", Context.MODE_PRIVATE)
        val db = AppDatabase.get(context)
        val date = LocalDate.now()
        val bounds = dayBounds(date)

        val tasks = db.taskDao().getAllOnce().filter {
            it.dueAt?.let { due -> due in bounds.first..bounds.second } == true
        }
        val notes = db.noteDao().getAllOnce().filter {
            it.createdAt in bounds.first..bounds.second
        }
        val favorites = db.favoriteDao().getAllOnce().filter {
            it.createdAt in bounds.first..bounds.second
        }

        var autoGenerated = false

        if (prefs.getBoolean("auto_summary", false)) {
            val key = SecureApiKeyStore.load(context)
            if (!key.isNullOrBlank()) {
                val ai = withContext(Dispatchers.IO) {
                    DeepSeekClient.dailySummary(
                        apiKey = key,
                        date = date.toString(),
                        completedTasks = tasks.filter { it.completed }.map { it.title },
                        pendingTasks = tasks.filter { !it.completed }.map { it.title },
                        notes = notes.map { it.content },
                        favorites = favorites.map { it.title }
                    )
                }

                if (ai.success) {
                    db.dailySummaryDao().upsert(
                        DailySummaryEntity(
                            dateKey = date.toString(),
                            content = ai.content,
                            model = DeepSeekClient.MODEL
                        )
                    )
                    autoGenerated = true
                }
            }
        }

        showDailyNotification(
            context = context,
            autoGenerated = autoGenerated,
            taskCount = tasks.size,
            noteCount = notes.size,
            favoriteCount = favorites.size
        )

        DailySummaryScheduler.schedule(
            context,
            prefs.getString("summary_time", "22:30") ?: "22:30"
        )

        return Result.success()
    }

    private fun dayBounds(date: LocalDate): Pair<Long, Long> {
        val zone = java.time.ZoneId.systemDefault()
        val start = date.atStartOfDay(zone).toInstant().toEpochMilli()
        val end = date.plusDays(1).atStartOfDay(zone).toInstant().toEpochMilli() - 1
        return start to end
    }

    private fun showDailyNotification(
        context: Context,
        autoGenerated: Boolean,
        taskCount: Int,
        noteCount: Int,
        favoriteCount: Int
    ) {
        val manager = context.getSystemService(NotificationManager::class.java)
        val channelId = "shiguangbox_daily"

        manager.createNotificationChannel(
            NotificationChannel(
                channelId,
                "每日整理",
                NotificationManager.IMPORTANCE_DEFAULT
            )
        )

        val text = if (autoGenerated) {
            "今天的 AI 总结已经替你整理好了。"
        } else {
            "今天有 " + taskCount + " 个待办、" + noteCount + " 条记录、" +
                favoriteCount + " 条收藏，来回顾一下吧。"
        }

        manager.notify(
            5105,
            NotificationCompat.Builder(context, channelId)
                .setSmallIcon(R.drawable.ic_stat_reminder)
                .setContentTitle("拾光盒 · 今天要结束啦")
                .setContentText(text)
                .setStyle(NotificationCompat.BigTextStyle().bigText(text))
                .setAutoCancel(true)
                .build()
        )
    }
}

class FavoriteAiWorker(
    appContext: Context,
    params: WorkerParameters
) : CoroutineWorker(appContext, params) {

    override suspend fun doWork(): Result {
        val context = applicationContext
        val id = inputData.getLong("favorite_id", 0L)
        if (id <= 0L) return Result.success()

        val key = SecureApiKeyStore.load(context)
        if (key.isNullOrBlank()) return Result.success()

        val dao = AppDatabase.get(context).favoriteDao()
        val item = dao.getAllOnce().firstOrNull { it.id == id } ?: return Result.success()

        val ai = withContext(Dispatchers.IO) {
            DeepSeekClient.summarizeFavorite(
                apiKey = key,
                title = item.title,
                platform = item.platform,
                rawText = item.rawText,
                note = item.note
            )
        }

        if (ai.success) {
            dao.update(
                item.copy(
                    aiSummary = ai.content,
                    aiTags = extractTagsForWorker(ai.content),
                    updatedAt = System.currentTimeMillis()
                )
            )
            return Result.success()
        }

        return if (runAttemptCount < 2) Result.retry() else Result.success()
    }

    companion object {
        fun enqueue(context: Context, favoriteId: Long) {
            val request = OneTimeWorkRequestBuilder<FavoriteAiWorker>()
                .setInputData(workDataOf("favorite_id" to favoriteId))
                .build()
            WorkManager.getInstance(context).enqueue(request)
        }
    }
}

private fun extractTagsForWorker(summary: String): String {
    return summary.lineSequence()
        .dropWhile { !it.contains("建议标签") }
        .drop(1)
        .firstOrNull { it.isNotBlank() }
        ?.trim()
        ?.removePrefix("：")
        ?.removePrefix(":")
        ?.trim()
        .orEmpty()
}
